[package]
name = "steamwebapi"
version = "0.1.0"
authors = ["Jackz <me@jackz.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0.126", features = ['derive'] }
serde_json = "1.0.64"